plugin-management:
  plugins-path: ./plugins

sts:
  resource-servers:
  - audience: "sts"
    jwks-url: "http://localhost:8888/pop"
  - audience: "my_audience"
    jwks-url: "http://localhost:8888/pop"
  - audience: "my_audience_2"
    jwks-url: "http://another_server:8080/pop"
  - audience: "sts-service-component-example"
    jwks-url: "http://localhost:8887/pop"
  - audience: "sts-service-component"
    jwks-url: "http://sts-service-component:8887/service-component/pop"
  keymanagement:
    rotation:
      check-interval: 5000
      enc-key-pairs:
        min-keys: 5
        enabled: true
      sign-key-pairs:
        min-keys: 5
        enabled: true
      secret-keys:
        min-keys: 5
        enabled: true
    persistence:
      container-name: adsts-container
      password: 0123456789ABCDEF
    keystore:
      password: FEDCBA9876543210
      type: UBER
      name: adsts-dev-keystore
      alias-prefix: adsts-dev-
      keys:
        enc-key-pairs:
          initial-count: 5
          algo: RSA
          sig-algo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validity-interval: 60000
          legacy-interval: 120000
        sign-key-pairs:
          initial-count: 5
          algo: RSA
          sig-algo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validity-interval: 60000
          legacy-interval: 120000
        secret-keys:
          initial-count: 5
          algo: AES
          size: 256
          validity-interval: 60000
          legacy-interval: 120000
